### PR TITLE
Array type syntax merge

### PR DESCRIPTION
**Pull request by seantalts**
I guess this also has the diff from master, making it a bit hard to see what's going on... but you can focus on parser.messages I guess?

### CODE REVIEW

**Comment by seantalts** [comment]
Or take a look at the commits? or I can just push it and you can take a look at it all together. Not sure what you'd prefer.

**Comment by rybern** [comment]
Thanks! The script will make things a little smoother.

I just added a dune dependency on the messages file so I could test it by removing messages manually.

I was afraid that --update-errors wouldn't preserve the message reuse format, but it seems like it just adds the comments back in inline, so that's fine.

**Comment by seantalts** [comment]
Ah yeah, nice. I was also thinking about calling the script as part of the
dune @update_messages target to add new ones. What do you think? I could
also make a script that, for any message sentences that lead to the same
error message, we automatically collapse the auto generated state comments
such that those comments are shown only for one of the grouped sentences.
How does that sound?

**Comment by rybern** [comment]
Both of those sound great! The latter one is what I've been meaning to get off my butt and do. Another thing would be to add a test that makes sure there aren't any stubs left in the messages file (i.e. `grep TODO` has no output).

**Comment by seantalts** [comment]
Oh yeah! That would be excellent. I could probably work on some of this
tonight if it’s helpful - any preferences for what I should look at?

**Comment by rybern** [comment]
No preference, anything would be helpful!

**Pull request merged**
